- hosts: localhost
  vars_files:
    - /root/ansible/include/vars.yml

  tasks:
  - name: provision web server
    ec2:
      key_name: "{{ key_name }}"
      instance_type: t2.micro
      image: "{{ ami_id }}"
      wait: yes
      count: 1
      vpc_subnet_id: "{{ subnet_id }}"
      group_id: "{{ sg_id }}"
      region: "{{ region }}"
      assign_public_ip: yes
      user_data: "{{ user_data }} "
      instance_tags:
        function: webserver
        git_ver: "{{ git_ver }}"
    register: ec2_result

  - name: wait for ssh
    local_action: wait_for port=22 host="{{ item.public_ip }}" search_regex=OpenSSH delay=10
    with_items: ec2_result.instances

  - name: add instances to elb
    ec2_elb:
      instance_id: "{{ item.id }}"
      ec2_elbs: "{{ elb_name }}"
      state: present
      region: "{{ region }}"
    with_items: ec2_result.instances
